"""Agent Manifest SDK - public API."""
from .models import (
    Manifest, ArtifactBindings,
    SystemPromptBinding, PolicyBundleBinding, ToolManifestBinding,
    ModelIdentityBinding, RagCorpusBinding, MemoryBaselineBinding,
    MemoryCheckpointBinding,
    DecisionTraceBinding, AuditCheckpointBinding, SupplyChainBinding,
    DelegationHop, HitlRecord, HitlApproval, ManifestSignature,
    ToolEntry, ScopeGrant, ApprovedScope, PoisoningScan, SlsaProvenance,
    AssuranceTest, AssuranceResult,
    Sbom, McpServer,
    EscalationPolicy, HitlRuntime,
    TransparencyLogEntry, InclusionProof,
    LogRetention, DataScope, OperationalLifecycle, DeclaredIntent,
    SourceBundleBinding,
    PolicyLanguage, EnforcementMode, DeploymentType, MemoryType, DriftPolicy,
    RugPullPolicy, TraceType, SbomFormat, SlsaLevel, PoisoningResult,
    ApprovalMethod, ApproverIdentityType, PrincipalType, DataClassification,
    CryptoProfile, SignatureAlgorithm, KeyType, RiskTier,
    ModelAttestationType, ManifestProfile, ArtifactName, SourceBundleFormat,
    OverrideMechanism, TimeoutAction,
)
from ._types import HashValue, ManifestId
from ._canonicalize import canonicalize, canonical_hash
from ._signing import (
    SIGNED_FIELDS,
    intent_hash,
    signing_pre_image,
    generate_ed25519, Ed25519KeyPair, Ed25519Signer, Ed25519Verifier,
)
from ._cose import (
    COSE_MANIFEST_VERSION, COSE_SIGN1_TAG, COSE_SIGN_TAG,
    ALG_EDDSA, ALG_ML_DSA_65,
    MEDIA_TYPE_MANIFEST_COSE, MEDIA_TYPE_MANIFEST_JSON,
    HDR_RECEIPTS, LABEL_ATTESTATION, LABEL_APPROVALS,
    cose_payload, payload_hash,
    sign_manifest_cose, sign_cose_sign1, sign_cose_sign_hybrid,
    attach_receipt, attach_attestation, attach_approvals, attach_unprotected,
    decode_cose_manifest, verify_cose_manifest,
    CoseVerification, CoseSignature,
    CoseError, CoseStructureError, CoseVersionError, CoseDowngradeError,
    CoseKeyError,
)
from ._providers import (
    AttestationReport, AttestationUnavailableError, RuntimeAttestationReport,
    TPMProvider,
)
from ._hw_providers import (
    AzureCVMProvider, SEVSNPProvider, TDXProvider, OPAQUEProvider,
)
from ._attestation import (
    verify_attestation_chain, ChainVerificationResult, SignatureStatus,
)
from ._snp_verify import (
    SIG_ALGO_ECDSA_P384_SHA384, SNP_OFFSETS, SNP_REPORT_LEN,
    PLATFORM_INFO_BITS,
    SnpReport, SnpPlatformInfo, SnpVerificationError,
    parse_snp_report, parse_platform_info, appraise_platform_info,
    parse_hcl_report, load_snp_cert_chain,
    verify_snp_signature, verify_vcek_chain, verify_runtime_data_binding,
    fetch_vcek,
)
from ._cert_chain import verify_cert_chain, CertChainError
from ._tdx_verify import (
    TdxQuote, TdxQuoteSignature, TdxVerificationError,
    parse_tdx_quote, parse_tdx_quote_signature, verify_tdx_quote,
)
from ._tpm_verify import (
    TPM_ST_ATTEST_NV, NvCertifyInfo, ParsedSignature, TpmAttest, TpmNvCertify, TpmQuote,
    TpmVerificationError,
    parse_nv_certify_info, parse_tpm_attest, parse_tpm_nv_certify, parse_tpm_quote,
    parse_tpmt_signature, verify_tpm_quote,
)
from ._verify import (
    verify_manifest,
    verify_runtime_report,
    VerificationContext, VerificationResult, ConfigurationAssurance,
    AgentCorrelation,
    verification_context_hash, derive_runtime_nonce,
    OverallResult, FieldResult, DelegationResult, HitlResult,
    FieldsVerified, MismatchDetail, EvidencePack,
    RevocationStore, RevocationRecord,
)
from ._trace import (
    verify_trace_envelope, verify_evidence_pack,
    trace_signing_pre_image, evidence_pack_pre_image, compute_pack_hash,
    TraceStatus, TraceVerificationResult, EvidencePackVerificationResult,
    TRACE_REQUIRED_FIELDS, TRACE_VERIFICATION_RESULTS, INADMISSIBLE_RESULTS,
)
from ._delegation import (
    verify_delegation_chain,
    verify_hitl_approval,
    delegation_depth_exceeded,
    DelegationHopSigner,
    HitlApprovalSigner,
)
from ._plugins import (
    PluginBundleError,
    PluginSkill,
    DeclaredMcpServer,
    PluginBundle,
    PluginManifestReference,
    PluginReferenceResult,
    PluginReferenceStatus,
    load_plugin_bundle,
    bundle_digest,
    bundle_reference_digest,
    plugin_manifest_reference,
    verify_plugin_manifest_reference,
    system_prompt_binding_from_bundle,
    PLUGIN_MANIFEST_EXTENSION,
    SUPPORTED_PLUGIN_SCHEMAS,
)

__all__ = [
    "Manifest", "ArtifactBindings",
    "SystemPromptBinding", "PolicyBundleBinding", "ToolManifestBinding",
    "ModelIdentityBinding", "RagCorpusBinding", "MemoryBaselineBinding",
    "MemoryCheckpointBinding",
    "AssuranceTest",
    "AssuranceResult",
    "AuditCheckpointBinding",
    "DecisionTraceBinding", "SupplyChainBinding",
    "DelegationHop", "HitlRecord", "HitlApproval", "ManifestSignature",
    "ToolEntry", "ScopeGrant", "ApprovedScope", "PoisoningScan", "SlsaProvenance",
    "Sbom", "McpServer",
    "EscalationPolicy", "HitlRuntime",
    "TransparencyLogEntry", "InclusionProof",
    "LogRetention", "DataScope", "OperationalLifecycle", "DeclaredIntent",
    "SourceBundleBinding",
    "PolicyLanguage", "EnforcementMode", "DeploymentType", "MemoryType", "DriftPolicy",
    "RugPullPolicy", "TraceType", "SbomFormat", "SlsaLevel", "PoisoningResult",
    "ApprovalMethod", "ApproverIdentityType", "PrincipalType", "DataClassification",
    "CryptoProfile", "SignatureAlgorithm", "KeyType", "RiskTier",
    "ModelAttestationType", "ManifestProfile", "ArtifactName", "SourceBundleFormat",
    "OverrideMechanism", "TimeoutAction",
    "HashValue", "ManifestId",
    "canonicalize", "canonical_hash",
    "SIGNED_FIELDS", "signing_pre_image", "intent_hash",
    "generate_ed25519", "Ed25519KeyPair", "Ed25519Signer", "Ed25519Verifier",
    "COSE_MANIFEST_VERSION", "COSE_SIGN1_TAG", "COSE_SIGN_TAG",
    "ALG_EDDSA", "ALG_ML_DSA_65",
    "MEDIA_TYPE_MANIFEST_COSE", "MEDIA_TYPE_MANIFEST_JSON",
    "HDR_RECEIPTS", "LABEL_ATTESTATION", "LABEL_APPROVALS",
    "cose_payload", "payload_hash",
    "sign_manifest_cose", "sign_cose_sign1", "sign_cose_sign_hybrid",
    "attach_receipt", "attach_attestation", "attach_approvals",
    "attach_unprotected", "decode_cose_manifest", "verify_cose_manifest",
    "CoseVerification", "CoseSignature",
    "CoseError", "CoseStructureError", "CoseVersionError", "CoseDowngradeError",
    "CoseKeyError",
    "AttestationReport", "AttestationUnavailableError", "RuntimeAttestationReport",
    "TPMProvider", "AzureCVMProvider", "SEVSNPProvider", "TDXProvider", "OPAQUEProvider",
    "verify_attestation_chain", "ChainVerificationResult", "SignatureStatus",
    "SIG_ALGO_ECDSA_P384_SHA384", "SNP_OFFSETS", "SNP_REPORT_LEN",
    "PLATFORM_INFO_BITS",
    "SnpReport", "SnpPlatformInfo", "SnpVerificationError",
    "parse_snp_report", "parse_platform_info", "appraise_platform_info",
    "parse_hcl_report", "load_snp_cert_chain",
    "verify_snp_signature", "verify_vcek_chain", "verify_runtime_data_binding",
    "fetch_vcek",
    "verify_cert_chain", "CertChainError",
    "TdxQuote", "TdxQuoteSignature", "TdxVerificationError",
    "parse_tdx_quote", "parse_tdx_quote_signature", "verify_tdx_quote",
    "TPM_ST_ATTEST_NV", "NvCertifyInfo", "ParsedSignature", "TpmAttest", "TpmNvCertify", "TpmQuote",
    "TpmVerificationError", "parse_nv_certify_info", "parse_tpm_attest", "parse_tpm_nv_certify",
    "parse_tpm_quote", "parse_tpmt_signature", "verify_tpm_quote",
    "verify_manifest", "verify_runtime_report",
    "VerificationContext", "VerificationResult", "ConfigurationAssurance",
    "AgentCorrelation",
    "verification_context_hash", "derive_runtime_nonce",
    "OverallResult", "FieldResult", "DelegationResult", "HitlResult",
    "FieldsVerified", "MismatchDetail", "EvidencePack",
    "RevocationStore", "RevocationRecord",
    "verify_trace_envelope", "verify_evidence_pack",
    "trace_signing_pre_image", "evidence_pack_pre_image", "compute_pack_hash",
    "TraceStatus", "TraceVerificationResult", "EvidencePackVerificationResult",
    "TRACE_REQUIRED_FIELDS", "TRACE_VERIFICATION_RESULTS", "INADMISSIBLE_RESULTS",
    "verify_delegation_chain", "verify_hitl_approval", "delegation_depth_exceeded",
    "DelegationHopSigner", "HitlApprovalSigner",
    "PluginBundleError", "PluginSkill", "DeclaredMcpServer", "PluginBundle",
    "PluginManifestReference", "PluginReferenceResult", "PluginReferenceStatus",
    "load_plugin_bundle", "bundle_digest", "bundle_reference_digest",
    "plugin_manifest_reference", "verify_plugin_manifest_reference",
    "system_prompt_binding_from_bundle", "PLUGIN_MANIFEST_EXTENSION",
    "SUPPORTED_PLUGIN_SCHEMAS",
]
